# Makefile for the Dummy pass
ROOT=../../..

PASSNAME := slicer
OBJS := Kleerer.o ModStats.o Slicing/FunctionStaticSlicer.o Slicing/PostDominanceFrontier.o Slicing/Prepare.o Slicing/StaticSlicer.o Callgraph/Callgraph.o Languages/LLVM.o Modifies/Modifies.o PointsTo/PointsTo.o Slicer.o

include ../Makefile.inc
