#!/bin/bash

PROC_NAME=mysqld
BIN_PATH=`pwd`/install/libexec/mysqld
RUN_DEPS=""

. ../scripts/include/cmdctl.inc

mode=$1
shift || mode="no_action"

case "$mode" in
  *)
    cmdctl_client_action $mode $*
    ;;
esac

