# Makefile for the preparation pass towards hybrid recovery
ROOT=../../..
CXXFLAGS+=-std=c++11
include $(ROOT)/Makefile.inc
PASSNAME := hybprep
OBJS := HybPrepPass.o
INCLUDES = -I../include -I../../

include ../Makefile.inc
