# Makefile for the EDFI pass
ROOT=../../..

PASSNAME := edfi
OBJS := FaultInjector.o  Fault.o Backports.o MapFile.o
HEADERS =  Fault.h
CFLAGS  += -DEDFI_FORBID_SWITCH_FLAGS

INCLUDES = -I../include

include ../Makefile.inc
