# Makefile for the inliner pass towards hybrid recovery
ROOT=../../..
CXXFLAGS+=-std=c++11
include $(ROOT)/Makefile.inc
PASSNAME := hybinline
OBJS := HybInlinePass.o
INCLUDES = -I../include -I../../

include ../Makefile.inc
