# Makefile for the hybrid recovery pass
ROOT=../../..
CXXFLAGS+=-std=c++11
include $(ROOT)/Makefile.inc
PASSNAME := hybrcvry
OBJS := HybRcvryPass.o
INCLUDES = -I../include -I../../

include ../Makefile.inc
